//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vidly_Dec_2019.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movy
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int GenreId { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<int> NumberInStock { get; set; }
    
        public virtual Genre Genre { get; set; }
    }
}
